### ISSUE TITLE
Get this working correctly under Travis-CI

### ISSUE THREAD

**Issue by davorg** [davorg/audiofile-info-ogg-vorbis-header#1]
There still seems to be a problem loading running this on Travis-CI. The problem is with loading the MO3 libraries.

**Comment by Git-Jiro** [comment]
I am going to take a look at this!

**Comment by davorg** [comment]
That would be great. Thanks.

**Comment by davorg** [comment]
Looks like [your PR](https://github.com/davorg/audiofile-info-ogg-vorbis-header/pull/2) fixed this. Thanks for your help.
